package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"ethparser/graph/model"
)

// Blocks is the resolver for the blocks field.
func (r *queryResolver) Blocks(ctx context.Context, filter *model.BlockFilter) ([]*model.Block, error) {
	if filter == nil {
		return r.BlockFetcher.Blocks(), nil
	}

	for _, b := range r.BlockFetcher.Blocks() {
		if b.Number == *filter.Number {
			return []*model.Block{
				b,
			}, nil
		}
	}
	return nil, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
