// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	Number       int            `json:"number"`
	Transactions []*Transaction `json:"transactions"`
}

type BlockFilter struct {
	Or     []*BlockFilter `json:"OR"`
	And    []*BlockFilter `json:"AND"`
	Number *int           `json:"number"`
}

type Transaction struct {
	Hash     string `json:"hash"`
	Nonce    int    `json:"nonce"`
	Value    string `json:"value"`
	GasPrice int    `json:"gas_price"`
	Gas      int    `json:"gas"`
	Type     int    `json:"type"`
	To       string `json:"to"`
	From     string `json:"from"`
	Data     string `json:"data"`
	Address  string `json:"address"`
}
