// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	Number       int            `json:"number"`
	Transactions []*Transaction `json:"transactions"`
}

type Transaction struct {
	Hash  string `json:"hash"`
	Value string `json:"value"`
	To    string `json:"to"`
	Gas   int    `json:"gas"`
	Data  string `json:"data"`
}
